version: "#{build}"
pull_requests:
  do_not_increment_build_number: true
clone_depth: 5
cache:
  - C:\projects\binaries -> .appveyor.yml, .appveyor
configuration:
  - Release
  - Debug
before_build:
  - cmd: call .appveyor\appveyor_helper.bat %CONFIGURATION%
build_script:
  - cmd: call "%VS90COMNTOOLS%vsvars32.bat"
  - cmd: vcbuild win_configure\pbs_windows_VS2008.sln "%CONFIGURATION%|Win32"
after_build:
  - cmd: call .appveyor\generate_installer.bat %CONFIGURATION%
before_test:
  - cmd: net user %USERNAME% pbS@123
  - ps: copy c:\projects\win_build\msi\PBSPro_*.msi PBSPro.msi
  - cmd: msiexec /quiet /qn /norestart /i c:\projects\pbspro\PBSPro.msi
  - cmd: refreshenv
  - cmd: C:\PROGRA~2\PBS\exec\python\python.exe C:\PROGRA~2\PBS\exec\etc\win_postinstall.py -u %USERNAME% -p pbS@123
test_script:
after_test:
  - ps: rm PBSPro.msi
  - ps: copy c:\projects\win_build\msi\PBSPro_*.msi .
artifacts:
  - path: '*.msi'
deploy: off
